# Local Airflow config overrides applied on top of the defaults generated by
# `airflow db migrate`. Kept minimal — most settings should come from env
# variables (AIRFLOW__SECTION__KEY=value) so they can be overridden per
# developer via the Notebook CR.
#
# Place at $AIRFLOW_HOME/airflow_local_settings.py if you want to extend.

# Example: cap task log retention to keep the PVC small
# DEFAULT_LOGGING_CONFIG = {
#     'handlers': {
#         'task': {
#             'backupCount': 3,
#         }
#     }
# }
